BRAVE_API_KEY=op://Personal/MCP Server Env/BRAVE_API_KEY
NOTION_TOKEN=op://Personal/MCP Server Env/NOTION_TOKEN
GITHUB_PERSONAL_ACCESS_TOKEN=op://Personal/MCP Server Env/GITHUB_PERSONAL_ACCESS_TOKEN
workspaceFolder=d:\work\
ANTHROPIC_API_KEY=op://Personal/MCP Server Env/ANTHROPIC_API_KEY
